### ISSUE TITLE
flux:field.file not working in flux:form.object

### ISSUE THREAD

**Issue by achim71** [FluidTYPO3/flux#1375]
Hi, 

With below config it is not possible to add an element to the selection in the backend.  It works as soon as i remove the flux:filed.file.
The file tag works fine when used outside of an flux:form.section.

```
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">

	<f:layout name="Content" />

	<f:section name="Configuration">
		<flux:form id="list" options="{group: 'Website'}">            					
            <flux:form.section name="settings.list" label="Liste">                
                <flux:form.object name="element" label="Element">
                    <flux:field.input name="title" label="Titel"/>                                  
                    <flux:field.text name="text" label="Text"/>
                    <flux:field.file name="image" label="Bild" required="1" maxItems="1" minItems="1"/>
                </flux:form.object>                
            </flux:form.section>
        </flux:form>
	</f:section>
    <f:section name="Main">
        
	</f:section>
</div>
```
I use typo3 8.6.1 / flux 8.1.0

**Comment by aarree** [comment]
Hi,
Same here. Also if i try to select an image I get this error.
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1288965219: $className must be a non empty string. | InvalidArgumentException thrown in file typo3core/typo3_src-8.6.1/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3870`

typo3 8.6.1 / flux 8.1.0

**Comment by dacostafilipe** [comment]
Same problem here. I get this error:
`#1476107295: PHP Warning: Invalid argument supplied for foreach() in /home/vagrant/Projects/Typo3/typo3_src-8.6.1/typo3/sysext/backend/Classes/Form/Element/GroupElement.php line 138`

**Comment by Sebastian-Habiger** [comment]
A simple workaround for me was to add the following line to my ext_tables.php:

$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ElementBrowsers']['file_reference'] = $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ElementBrowsers']['file'];

**Comment by NamelessCoder** [comment]
Please report this issue on the TYPO3 core bug tracker, https://forge.typo3.org/projects/typo3cms-core/issues. Flux does not control the rendering or handling of the actual input fields (we only generate TCA). If the same component works in one place but fails in another, that's probably an issue with the FormEngine's method of handling component dependencies when component is used in a specific way.

**Comment by achim71** [comment]
I lack the technical insight into the framework to write such an bug report. Hope someone picks up.

**Comment by uscreenFikret** [comment]
In the current TYPO3 8.7.0 LTS I have solved it as follows:

Add in `AdditionalConfiguration.php` or in one of the` ext_tables.php`

```
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ElementBrowsers']['file_reference'] = "TYPO3\CMS\Recordlist\Browser\FileBrowser";
```

**Comment by NamelessCoder** [comment]
@uscreenFikret If that works it could be set as part of the default/factory configuration of TYPO3. If you haven't already, please report this finding on the URL I gave above, so the core team can evaluate it :)

**Comment by uscreenFikret** [comment]
Done https://forge.typo3.org/issues/80727

**Comment by maryisdead** [comment]
Out of curiosity, @achim71 and @dacostafilipe:

Did
```
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ElementBrowsers']['file_reference'] = $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ElementBrowsers']['file'];
```
or
```
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ElementBrowsers']['file_reference'] = "TYPO3\CMS\Recordlist\Browser\FileBrowser";
```
fix the issue for you? I do have these things set but still get

```
PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/somepath/vendor/typo3/cms/typo3/sysext/backend/Classes/Form/Element/GroupElement.php line 138
```

**Comment by dacostafilipe** [comment]
@maryisdead 

This works for me (typo3 8.7.1, flux 8.2.1):

`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ElementBrowsers']['file_reference'] = "TYPO3\\CMS\\Recordlist\\Browser\\FileBrowser`

**Comment by maryisdead** [comment]
@dacostafilipe Thanks!

It wasn't actually the double backslashes but rather that I had typo3/cms 8.6.1 installed. Updating to 8.7.1 fixed it. Thanks again!
