### ISSUE TITLE
Language handling issues flux > 9.2

### ISSUE THREAD

**Issue by TheWirsing** [FluidTYPO3/flux#1747]
Since version 9.3 I have problems with the language handling in the backend. 

1. In page module in language view I see the nested elements of the currently selected language. For all other languages I see only the parent container. After switching language I see the nested elements for that language but not the others.
2. When translating a page (in copy mode) the processing animation gets stuck. After reloading the backend I see, that all but the nested elements where translated. This message in the logs seems to be related: 
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 8 passed to FluidTYPO3\Flux\Integration\HookSubscribers\DataHandlerSubscriber::recursivelyCopyChildRecords() must be of the type array, boolean given, called in /var/www/app/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php on line 240 | TypeError thrown in file /var/www/app/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php in line 288. Requested URL: http://test.local/typo3/index.php?route=%%2Fajax%%2Frecords%%2Flocalize&token=--AnonymizedToken--&pageId=2510&srcLanguageId=0&destLanguageId=1&action=copyFromLanguage&uidList%%5B%%5D=31128&uidList%%5B%%5D=31129`

Maybe it's helpful to mention that I migrated from fluidconent and fluidpages recently. In version 9.2 I don't experience the described problems.

**Comment by TheWirsing** [comment]
I found out that the problems occur also using the most recent test_provider_extension in Typo3 V9.5.14.

**Comment by buepro** [comment]
I see a similar behaviour with `flux 9.3.2`. When using the `strict translation work flow` just the container gets translated into the new language where the containing content elements are the same as for the source language. It looks like just the outmost element gets correctly created in the target language.

**Comment by sllg-org** [comment]
Same here, `sys_language_mode = strict` nested flux-ce are not translated.
With 9.2.0 translation-things went well.

**Comment by mkrappitz** [comment]
Can confirm all of this!

**Comment by jgreiner** [comment]
Same with me. only downgrading to flux 9.2.0 and reinstalling fluidpages fixed this issue

**Comment by glucka** [comment]
I can confirm this too

**Comment by glucka** [comment]
I can confirm this too

**Comment by kimchristiansen** [comment]
Same here. 
Flux 9.3.4
TYPO3 9.5.14
No fluidpages

New TYPO3 Setup (Composer based) no upgrade from fluidcontent.
sys_language_mode = strict

The content elements in the grid are getting translated correctly in translate mode. Frontend seems correct too. But in the backend  the content element of the original language is shown in the translated grid.

**Comment by monosize** [comment]
@NamelessCoder A workaround seems possible with the following change:
Exchange line typo3conf/ext/flux/Classes/Integration/PreviewView.php:351 ```$dblist->tt_contentConfig['sys_language_uid'] = (int) $moduleData['language'];``` with ```$dblist->tt_contentConfig['sys_language_uid'] = (int) $row['sys_language_uid'];``` 

Maybe someone can double check.

**Comment by NamelessCoder** [comment]
@monosize Do you know what `$moduleData['language']` has to contain in order to cause the problem? This setting should be trustworthy in both "Columns" and "Languages" modes so I'm not sure what would be different. I'm also not sure it's safe to use `$row['sys_language_uid']` if the parent record's language is set to "All languages" (-1)...

**Comment by monosize** [comment]
@NamelessCoder The problem occurs only in the page view "languages". The selected language in this view is then used in the flux grid in all languages, see screenshots.

 "All Languages"(-1) seems to work. Content elements with the selection "All languages" are always output in the main language "sys_language_uid = 0". 

![lang0](https://user-images.githubusercontent.com/1583746/78508917-aa070380-778a-11ea-98ba-28f33cbde993.png)
![lang1](https://user-images.githubusercontent.com/1583746/78508924-b2f7d500-778a-11ea-9b9a-d297d6a40497.png)

**Comment by instruccionesaldorso** [comment]
@monosize Could you provide a patch with your solution for the rest of us test it?

**Comment by monosize** [comment]
@instruccionesaldorso here is the patch. You can use git apply.
tested with flux version 9.3.2 
We have been using it for 4 days in a production system and it runs without any problems. 
```
diff --git a/Classes/Integration/PreviewView.php b/Classes/Integration/PreviewView.php
index 4c296730..c6193efb 100644
--- a/Classes/Integration/PreviewView.php
+++ b/Classes/Integration/PreviewView.php
@@ -348,7 +348,7 @@ class PreviewView extends TemplateView
         $dblist->tt_contentConfig['showInfo'] = 1;
         $dblist->tt_contentConfig['single'] = 0;
         $dblist->nextThree = 1;
-        $dblist->tt_contentConfig['sys_language_uid'] = (int) $moduleData['language'];
+        $dblist->tt_contentConfig['sys_language_uid'] = (int) $row['sys_language_uid'];
         $dblist->tt_contentConfig['showHidden'] = $showHiddenRecords;
         $dblist->tt_contentConfig['activeCols'] = $columnsAsCSV;
         $dblist->tt_contentConfig['cols'] = $columnsAsCSV;
```

**Comment by instruccionesaldorso** [comment]
I applied the patch to our development system and it works like a charm as well.
We'll wait for Claus' answer to be integrated if there are no side-effects then.

**Comment by TrueType** [comment]
Tested with f83a100561eea5f8d058e83d69e7a06888158ad4 and behaviour was no better. Add proposed change in PreviewView.php by hand, which fixed it.

**Comment by jonaseberle** [comment]
It works for me with dev-development f83a100 (TYPO3 9.5.15)

**Comment by glucka** [comment]
f83a100 solve this issue

**Comment by TrueType** [comment]
Are we talking about the same?
- the patch provided @monosize is irrelevant?
- as I said I still get the behaviour quite obvious - see screenshot and my flux CE definition

![grafik](https://user-images.githubusercontent.com/141848/79550177-463cde80-8098-11ea-9e09-1f2ac31604cc.png)

	<f:section name="Configuration">
		{v:variable.typoscript(path: 'plugin.tx_fluidcontentbootstrap.settings') -> v:variable.set(name: 'settings')}
		{f:if(condition: settings.gridColumns, then: settings.gridColumns, else: 12) -> v:variable.set(name:'countOfGridColumns')}
		<flux:form id="row" options="{useTypoScript: 0, group: 'mygroupname'}">
			<flux:form.section name="columns">
				<flux:form.object name="column">
					<flux:field.select
                            name="class"
                            items="{f:render(section: 'Value', arguments: {iteration: iteration})-> v:iterator.loop(count: countOfGridColumns, iteration: 'iteration', minimum: 1)}"
                            label="Columns: numberOfColumns"
                    />
					<flux:field.input name="additionalClass"/>
				</flux:form.object>
			</flux:form.section>
			<flux:grid>
				<flux:grid.row>
					<v:condition.type.isArray value="{columns}">
						<f:for each="{columns}" as="sectionObject" iteration="iteration">
							<v:variable.set name="width" value="{sectionObject.column.class -> v:format.substring(start: 6)}"/>
							<v:variable.set name="percent" value="{width  -> v:math.division(b: countOfGridColumns) -> v:math.product(b: 100) -> v:math.round(decimals: 2)}"/>
							<flux:grid.column colPos="{iteration.index}" style="width: {percent}%; min-width: 600px !important;" name="column{iteration.cycle}" label="{percent}%"/>
						</f:for>
					</v:condition.type.isArray>
				</flux:grid.row>
			</flux:grid>
		</flux:form>
	</f:section>

**Comment by NamelessCoder** [comment]
Issue contains two bug reports in one, the current state is that only the second of the two is fixed (performing translation).

**Comment by jonaseberle** [comment]
I didn't test well. Inside flux elements (grids) it is not solved! Sorry for the misinformation.

**Comment by glucka** [comment]
exactly, in columns view works f83a100 with grids too, in language view does not

**Comment by TrueType** [comment]
Flux running nicely with all fixes from above I run into a similar error:

```
 Argument 3 passed to 
 FluidTYPO3\Flux\Provider\ProviderResolver::resolvePrimaryConfigurationProvider() must be of the 
 type array or null, bool given, called in 
 /kunden/506260_70199/webseiten/TYPO3V9/instances/20200323 -153100/webroot/web/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php on line 339

 at FluidTYPO3\Flux\Provider\ProviderResolver->resolvePrimaryConfigurationProvider('tt_content', null, false, null, 'FluidTYPO3\\Flux\\Provider\\Interfaces\\GridProviderInterface')

 at FluidTYPO3\Flux\Integration\HookSubscribers\DataHandlerSubscriber->getParentAndRecordsNestedInGrid('tt_content', 1801, 'uid, pid')

 at FluidTYPO3\Flux\Integration\HookSubscribers\DataHandlerSubscriber->cascadeCommandToChildRecords('tt_content', 1801, 'delete', true, object(TYPO3\CMS\Core\DataHandling\DataHandler))

 at FluidTYPO3\Flux\Integration\HookSubscribers\DataHandlerSubscriber->processCmdmap_beforeStart(object(TYPO3\CMS\Core\DataHandling\DataHandler))
```


I am working in list module on an custom extension TCA record, which has a property type=inline and foreign_table=tt_content. Saving the record the exception comes. Behaviour is probably only because of translations. After I delete such inline record (delete button with the inline) in the translated record and change to the standard translation and save, the error is shown. 

Probably not too severe as the way to reproduce may be rarely encountered.. do in a separate ticket?
