### ISSUE TITLE
BUG: Nested grid-elements are not overlayed/translated properly in multilanguage site in version 10.1.0.

### ISSUE THREAD

**Issue by SylwesterDev** [FluidTYPO3/flux#2204]
**I have checked that the bug exists in the `dev-development` branch**
_Yes_

**I have checked that there are no already open issues or recently closed issues about this bug**
_Yes_

**Describe the bug**
By multilanguages pages grid elements always displaying "default" language, and not the selected one.

**To Reproduce**
1. Create page with at least 2 languages. (in my case DE as default and PL as secondary language)
2. Create grid element container and fill it with some content. Do the same for second language, or just translate default language elements. In my test case I have the content in "connected mode".
3. Open page using secondary language (in my case PL).
4. The grid container itself as well as content elements inside grid container are shown in default language (DE), and not as expected in secondary language (PL).

**Expected behavior**
Expected is to display content in selected language.

**Screenshots**

![image](https://github.com/user-attachments/assets/b3e14152-a915-4c14-b6fe-61c0d259bf28)

![image](https://github.com/user-attachments/assets/5e27ca49-0ba8-443a-bc21-4080e7c952e9)

![image](https://github.com/user-attachments/assets/5d8390bb-fc31-496c-9d31-63bbd5cb1841)

![image](https://github.com/user-attachments/assets/b590fe0c-e353-4e2c-b894-10b7bf638d1c)

**Additional context**
The function "getSingle" in class "FluidTYPO3\Flux\Service\WorkspacesAwareRecordService" return data for selected row without variable "_LOCALIZED_UID", so it deliver different data than previous implementation "$record = $contentObject->data;". The "_LOCALIZED_UID" is missing so the content elements cannot be rendered in correct language.

Here small diff which is fixing the issue:
[flux-lang.txt](https://github.com/user-attachments/files/18336856/flux-lang.txt)

**Comment by dacostafilipe** [comment]
Same here with 12.4.26

**Comment by ChristianOsswald** [comment]
Maybe this error is related to this issue:

FluidTYPO3\Flux\Utility\ColumnNumberUtility::calculateParentUid(): Argument #1 ($colPos) must be of type int, string given, 
called in /vendor/fluidtypo3/flux/Classes/Integration/HookSubscribers/ColumnPositionItems.php on line 30

I can't translate elements without 503 error.
TYPO3 v12.4.6
Flux v10.1.1

When I cast (int) at line 30 in ColumnPositionItems.php translation process seems to work but in frontend default language is shown as described above.

**Comment by dacostafilipe** [comment]
> Maybe this error is related to this issue:
> 
> FluidTYPO3\Flux\Utility\ColumnNumberUtility::calculateParentUid(): Argument [#1](https://github.com/FluidTYPO3/flux/pull/1) ($colPos) must be of type int, string given, called in /vendor/fluidtypo3/flux/Classes/Integration/HookSubscribers/ColumnPositionItems.php on line 30
> 
> I can't translate elements without 503 error. TYPO3 v12.4.6 Flux v10.1.1
> 
> When I cast (int) at line 30 in ColumnPositionItems.php translation process seems to work but in frontend default language is shown as described above.

I don't think it's directly related, but I also had that issue and the rollback to 10.0.10 (ty @tim-baecker ) to solve the issue here also solved the issue you mention.

Funny part about your issue is that my user did not throw the 503, but most other users did. I had to reset my user settings (User Settings > Reset configuration > Reset user settings to default state) for my user to finally throw those 503s. It could explain why that issue slipped through testing. I compared both settings in the User Settings panel, but everything was identical. I will need to compare the user records in the database directly in the near future.

PS: If you open a new issue, can you please tag me?

**Comment by format-gmbh** [comment]
I can confirm this problem is present in TYPO3 version 13.4.8
patch from [SylwesterDev](https://github.com/SylwesterDev) works for me

**Comment by helfalt** [comment]
Hi @NamelessCoder ,
Is there any problem regarding this bugfix? 
If not, can you include the patch into the next releases?
Thx in advance

**Comment by NamelessCoder** [comment]
This problem should be fixed in https://github.com/FluidTYPO3/flux/commit/f71fe74e848718c3972a73af9cccb815c3aad183. If not, please ask for this issue to be reopened.

**Comment by dacostafilipe** [comment]
@NamelessCoder this does solve this issue, the frontend correctly shows the right language, but in the backend I still have the wrong language as described in the now closed #2246 

We will stay at 10.0.10 for now.

**Comment by vimar** [comment]
Same as @dacostafilipe, when using free mode, backend doesn't display any records inside nested grid elements even they are correctly displayed in frontend.

**Comment by swissdude** [comment]
If somebody still struggles with this, I found the solution (applies to Typo3 12.4. and Flux 11.1 - nested Flux-Grid-Elements - at least in `free mode`. Don't know about `connected mode`, but might be the same):

In the file `flux/Classes/Integration/Preview.php` on row 261:

`$context = $context->cloneForLanguage($language);`

This does indeed make a clone for the content element with the correct language. But `$context->getDrawingConfiguration()->setSelectedLanguageId()` still returns the original language-ID (which is usually '0'.

Just add the the following on the next line:

`$context->getDrawingConfiguration()->setSelectedLanguageId($language->getLanguageId());`

And - tadaa! - the translated nested elements are visible in the backend.

Took me while to figure this out, so if you wanna drop me a beer, feel free to ;)
