### ISSUE TITLE
BUG: Multilanguage output broken in frontend

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/flux#2246]
**I have checked that the bug exists in the `dev-development` branch**
_Yes._

**I have checked that there are no already open issues or recently closed issues about this bug**
_Yes._

**Describe the bug**
After updating flux from 10.0.9 to 11.0.3 in a TYPO3 12 to 13 update, all content from all flux elements in non-default languages is being rendered in the default language only in the frontend of the web-site. Everything worked fine in 12 and is broken in 13 with no config or other changes to the flux elements or the TYPO3 config. 
E.g. before the update it said "Efficient Learning instead of Trial & Error." in the first h1 in EN:
https://www.aemka.de/en/services/training-and-coaching.html
E.g. after it says "Effiziente Schulungen von erfahrenen Trainern" in the first h1 in EN, which is the text of this elements default language (DE):
https://dev.aemka.de/en/services/training-and-coaching.html
This erratic behaviour is the same for flux flexform fields as well as for using existing TCA fields of the core such as record.header.

For me this looks like a bug, unless there is something that needs to be changed after this described update. The TYPO3 language config looks as follows:

```yaml
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de
    direction: ''
    flag: de
    languageId: 0
    websiteTitle: aemka
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: gb
    languageId: 2
    websiteTitle: aemka
  -
    title: Spanisch
    enabled: true
    locale: es_ES.UTF-8
    hreflang: es
    base: /es/
    websiteTitle: ''
    navigationTitle: ES
    fallbackType: fallback
    fallbacks: '2'
    flag: es
    languageId: 3
```

If there is any additional info I should give, to understand this better, just tell me!

**Comment by rupasix** [comment]
Related: https://github.com/FluidTYPO3/flux/issues/2204

**Comment by ChristianOsswald** [comment]
Patch from https://github.com/FluidTYPO3/flux/issues/2204 wasn't applicable TYPO3 Version 13.4.13

**Comment by ChristianOsswald** [comment]
Here is my updated version for TYPO3 Version 13.4.13

[flux_fix-default-language.patch](https://github.com/user-attachments/files/20687335/flux_fix-default-language.patch)

**Comment by mkrappitz** [comment]
Great, that fixed the problem. Thank you so much! Hope this gets into the official flux soon.

**Comment by marcel-mattern** [comment]
Hello everyone,
thank you for the patch. Unfortunately, in the backend, the nested content elements are still in the original language. This issue does not occur with version 10.x, but it has been present since version 11.x.

**Comment by heydavee** [comment]
Still an issue with 11.0.7. Nested translations work fine with the patch above, but backend elements are still in the original language (visually).

<img width="1905" height="1021" alt="Image" src="https://github.com/user-attachments/assets/c0cf9f5e-c0ef-4e84-b6a9-0e30f7af760b" />

**Comment by NamelessCoder** [comment]
This problem should be fixed in https://github.com/FluidTYPO3/flux/commit/f71fe74e848718c3972a73af9cccb815c3aad183. If not, please ask for this issue to be reopened.

**Comment by vimar** [comment]
Similar to #2204 we still have some issues with translation in backend. I have just tested on development branch btw. You should reopen at least one issue.
